# Generated by Django 5.2.17 on 2026-08-13 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.PositiveBigIntegerField(default=0)),
                ('turnover', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('percentage_change', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('listed_shares', models.PositiveBigIntegerField(default=0)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.PositiveBigIntegerField(default=0)),
                ('turnover', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stocks.stock')),
            ],
            options={
                'ordering': ('date',),
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_history_date')],
            },
        ),
    ]
