"""Curated numbered NEPSE member directory for local demo/reference data.

Refresh through the official NEPSE Brokers' List before production use.
"""
BROKERS = [
    (1, "Kumari Securities Pvt. Limited"), (3, "Arun Securities Pvt. Ltd."),
    (4, "Opal Securities Investment Pvt. Ltd."), (5, "Market Securities Exchange Company Pvt. Ltd"),
    (6, "Agrawal Securities Pvt. Ltd"), (7, "J.F. Securities Company Pvt. Ltd"),
    (8, "Ashutosh Brokerage & Securities Pvt. Ltd"), (10, "Pragyan Securities Pvt. Ltd"),
    (11, "Malla & Malla Stock Broking Company Pvt. Ltd"), (13, "Thrive Brokerage House Pvt. Ltd"),
    (14, "Nepal Stock House Pvt. Ltd"), (16, "Primo Securities Pvt. Ltd"),
    (17, "ABC Securities Pvt. Ltd"), (18, "Sagarmatha Securities Pvt. Ltd"),
    (19, "Nepal Investment & Securities Trading Pvt. Ltd"), (20, "Sipla Securities Pvt. Ltd"),
    (21, "Midas Stock Broking Company Pvt. Ltd"), (22, "Siprabi Securities Pvt. Ltd"),
    (25, "Sweta Securities Pvt. Ltd"), (26, "Asian Securities Pvt. Ltd"),
    (28, "Shree Krishna Securities Ltd"), (29, "Trishul Securities And Investment Ltd"),
    (32, "Premier Securities Company Ltd"), (33, "Dakshinkali Investment Securities Pvt. Ltd"),
    (34, "Vision Securities Pvt. Ltd"), (35, "Kohinoor Investment and Securities Pvt. Ltd"),
    (36, "Secured Securities Ltd"), (37, "Swarnalaxmi Securities Pvt. Ltd"),
    (38, "Dipshika Dhitopatra Karobar Company Pvt. Ltd"), (39, "Sumeru Securities Pvt. Ltd"),
    (40, "Creative Securities Pvt. Ltd"), (41, "Linch Stock Market Ltd"),
    (42, "Sani Securities Company Ltd"), (43, "South Asian Bulls Pvt. Ltd"),
    (44, "Dynamic Money Managers Securities Pvt. Ltd"), (45, "Imperial Securities Co. Pvt. Ltd"),
    (46, "Kalika Securities Pvt. Ltd"), (47, "Neev Securities Pvt. Ltd"),
    (48, "Trishakti Securities Public Ltd"), (49, "Online Securities Limited"),
    (50, "Cristal Kanchenjunga Securities Pvt. Ltd"), (51, "Oxford Securities Pvt. Ltd"),
    (52, "Sundhara Securities Ltd"), (53, "Investment Management Nepal Pvt. Ltd"),
    (54, "Sewa Securities Pvt. Ltd"), (55, "Bhrikuti Stock Broking Co. Pvt. Ltd"),
    (56, "Sri Hari Securities Pvt. Ltd"), (57, "Aryatara Investment And Securities Pvt. Ltd"),
    (58, "Naasa Securities Company Ltd"), (59, "Deevyaa Securities & Stock House Pvt. Ltd"),
    (60, "Nagarik Stock Dealer Ltd"), (61, "Bhole Ganesh Securities Ltd"),
    (62, "Capital Max Securities Ltd"), (63, "Himalayan Brokerage Company Ltd"),
    (64, "Sun Securities Pvt. Ltd"), (65, "Sharepro Securities Private Ltd"),
    (66, "Miyo Securities Pvt. Ltd"), (67, "Property Wizard Ltd"),
    (68, "Elite Stock House Ltd"), (69, "Index Securities Ltd"),
    (70, "Infinity Securities Ltd"), (71, "Shubhakmana Securities Pvt. Ltd"),
    (72, "Hatemalo Financial Services Private Ltd"), (73, "Money World Share Exchange Pvt. Ltd"),
    (74, "Kalash Stock Market Pvt. Ltd"), (75, "NIMB Stock Markets Ltd"),
    (76, "Machhapuchchhre Securities Ltd"), (77, "Nabil Stock Dealer Ltd"),
    (78, "Garima Securities Ltd"), (79, "Pahi Investment"),
    (80, "Indira Securities Pvt. Ltd"), (81, "Aakashbhairab Securities Ltd"),
    (82, "N.M.B. Securities Ltd"), (83, "Sanima Securities Ltd"),
    (84, "Milkyway Share Broker Company Ltd"), (85, "Capital Hub Pvt. Ltd"),
    (86, "Stoxkarts Securities Ltd"), (87, "S.P.S.A. Securities Ltd"),
    (88, "Blue Chip Securities Ltd"), (89, "J.B.N.L Securities Ltd"),
    (90, "Sajilo Broker Ltd"), (91, "CBIL Securities Ltd"),
    (92, "Roadshow Securities Ltd"), (93, "Beni Securities Pvt. Ltd"),
    (94, "K.B.L. Securities Ltd"), (95, "Magnet Securities & Investment Company Pvt. Ltd"),
    (96, "Himalayan Securities Ltd"), (97, "RBB Securities Company Ltd"),
    (98, "Trademow Securities Private Ltd"), (99, "Prabhu Stock Market Limited"),
    (100, "Sunrise Securities Limited"), (101, "Apple Securities Private Ltd"),
]
