# Generated by Django 5.2.17 on 2026-08-13 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('broker_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('broker_number',),
            },
        ),
        migrations.CreateModel(
            name='FloorSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=64, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('trade_date', models.DateField(db_index=True)),
                ('trade_time', models.TimeField(blank=True, null=True)),
                ('buyer_broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='brokers.broker')),
                ('seller_broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='brokers.broker')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorsheets', to='stocks.stock')),
            ],
            options={
                'ordering': ('-trade_date', 'contract_number'),
                'indexes': [models.Index(fields=['stock', 'trade_date'], name='brokers_flo_stock_i_3bb86d_idx'), models.Index(fields=['buyer_broker', 'trade_date'], name='brokers_flo_buyer_b_e045e5_idx'), models.Index(fields=['seller_broker', 'trade_date'], name='brokers_flo_seller__9417be_idx')],
            },
        ),
    ]
